---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "znc-tls"
  namespace: selfhosted
spec:
  secretName: "znc-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "znc-admin.${SECRET_DOMAIN}"
  dnsNames:
    - "znc-admin.${SECRET_DOMAIN}"
