---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app znc
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: znc
      tag: 1.8.2

    podAnnotations:
      secret.reloader.stakater.com/reload: znc-tls

    env:
      TIMEZONE: "Australia/Perth"

    service:
      main:
        enabled: true
        type: LoadBalancer
        annotation:
          ingress.home.arpa/type: "external-auth"
        loadBalancerIP: "10.1.99.102"
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 1111
      http:
        enabled: true
        ports:
          https:
            port: 80

    ingress:
      main:
        enabled: false
      http:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          ingress.home.arpa/type: "external-auth"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "znc-admin.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: znc-config-pvc
        mountPath: /znc-data

      cert:
        enabled: true
        type: secret
        name: znc-tls
        mountPath: /config/tls
        readOnly: true

    resources:
      requests:
        cpu: 20m
        memory: 128M
      limits:
        memory: 512M
