---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: media-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1@sha256:690b6365728fe9012ad4cdfca38334992664596513dca187d1b93d2025205776

    DNS: 172.16.1.1

    addons:
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.35.0@sha256:a98d1ec99e09a1b806aff7f0c3d8a133a8ede7d3d7a250b62029a39a61f01525
        env:
          - name: VPN_SERVICE_PROVIDER
            value: protonvpn
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: media-gateway-vpnconfig
                key: OPENVPN_USER
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: media-gateway-vpnconfig
                key: OPENVPN_PASSWORD
          - name: SERVER_COUNTRIES
            valueFrom:
              secretKeyRef:
                name: media-gateway-vpnconfig
                key: SERVER_COUNTRIES
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

      netshoot:
        enabled: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: media-gateway-pod-gateway
      secret.reloader.stakater.com/reload: media-gateway-vpnconfig

    publicPorts:
      - IP: 10
        hostname: qbittorrent
        ports:
          - type: udp
            port: 61144
          - type: tcp
            port: 61144

    # routed_namespaces:
    #   - media

    settings:
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_TRAFFIC_PORT: "51820"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.1.99.0/24 10.42.0.0/16 10.43.0.0/16"
      VPN_LOCAL_CIDRS: "10.1.99.0/24 10.42.0.0/16 10.43.0.0/16"

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.9.0@sha256:4e169da5af107a9c6c784d3e03c89da07fad45f18358ab5b7177662df12d955a
