---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./calibre-web/ks.yaml
  - ./immich/ks.yaml
  - ./media-browser/ks.yaml
  - ./omegabrr/ks.yaml # TODO need to fix variables in config.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  # - ./plex-auto-languages/ks.yaml
  # - ./plex-meta-manager/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
