---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app shlink-api
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/shlinkio/shlink
      tag: 3.6.3-non-root
    env:
      DEFAULT_DOMAIN: &host "shlink.${SECRET_DOMAIN}"
      DISABLE_TRACKING_FROM: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      ENABLE_PERIODIC_VISIT_LOCATE: "true"
      IS_HTTPS_ENABLED: "true"
      PORT: &port 80
      # REDIS_PUB_SUB_ENABLED: "true"
      # REDIS_SENTINEL_SERVICE: redis-master
      # REDIS_SERVERS: >-
      #   redis-node-0.redis-headless.db.svc:26379,
      #   redis-node-1.redis-headless.db.svc:26379,
      #   redis-node-2.redis-headless.db.svc:26379
      TIMEZONE: "Australia/Perth"
    envFrom:
      - secretRef:
          name: shlink-api-secrets
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          ingress.home.arpa/type: "external"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 1Gi
