apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:fE9SMDStiFWup/7Eth1FqydYTHM0/qHYze5vqLqU1U7IOlQ/SKxgcH+gM//bn+y9bSg3L9WetKX2B70e,iv:pAlK4MKp5U4Fd6T6EKGjJZew+RW/N4YltpGgsuRFJCo=,tag:S0CAlua4EXvWlEXsIoO/hA==,type:str]
    username: ENC[AES256_GCM,data:Xmc2MNg=,iv:xN9JN1gOHotCDbKpvI1U9hYO3j1aY0685e00FGg3SYs=,tag:h1XkBpC8ZR9iphcNJvNh2A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmZHT05IUkJuM3RpNldK
            cVBTbWxIUExGZDlST2t2a1Y4M2hsbXRPM3pBCndOUzNtM29EODRDUm0xTUtkd0lC
            dDFReU9UNmxzb3kvRTRZdi8vTzVCNDgKLS0tIGlaT3VrM0NiSnZudnpYRTBhR0Zp
            cGRXL2J0a01EcUdzY1BvMDJ0ek9EK0EKVhljfJRSv8h0xe8efgV4YbAobRlNZ4Tv
            DnoPSttUV+R/LRlK27KZfHgX4M/kwkaXRCG7JYIUG5+xDZR53U7P1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-08T14:29:27Z"
    mac: ENC[AES256_GCM,data:INuQ/Qi0luuZ5nUrZDELg1NYO65/SH08GQGPA/UYnODygdVVHpw/2aJtZtrBtgfj6m97kfHVa3zSjdqy7VRYUaQh6r+J7ciVCIuIKn0Yo+UVvW6Rjz6J6/vDZtBWBq5v/5br8S+KyL9DBpGpxDMY47CNhl4LcZGoZCBV+d5SBcg=,iv:0gSzo33HKyKwkaB4RS3YPAN6Ufm0+aYRkVoNMPMuFMw=,tag:aqsGUEykGSwHRn/2aFKH7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
