---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr-config-pvc
  namespace: media-org
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
