---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:generate-cronjob
rules:
  - apiGroups:
      - "batch"
    resources:
      - cronjobs
    verbs:
      - create
      - update
      - delete
      - list
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno:generate-cronjob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:generate-cronjob
subjects:
  - kind: ServiceAccount
    name: kyverno
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:read-namespace
rules:
  - apiGroups: [""]  # Empty string represents the core API group
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno:read-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:read-namespace
subjects:
  - kind: ServiceAccount
    name: kyverno
    namespace: system
