---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tailscale-gateway
  namespace: vpn
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    serviceAccount:
      name: tailscale

    image:
      repository: ghcr.io/tailscale/tailscale
      tag: v1.44.0
    env:
      TZ: "Australia/Perth"
      TS_KUBE_SECRET: "tailscale-auth"
      SA_NAME: tailscale
      TS_USERSPACE: "true"
      TS_ROUTES: "${CLUSTER_CIDR},${SERVICE_CIDR}"
      TS_EXTRA_ARGS: "--advertise-exit-node"
    envFrom:
      - secretRef:
          name: tailscale-auth

    service:
      main:
        ports:
          http:
            port: &port 45387

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000

    ingress:
      main:
        enabled: false
