---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-org
resources:
  - ./helm-release.yaml
  - ./secret.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: plex-auto-languages
      app.kubernetes.io/instance: plex-auto-languages
