---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-org
resources:
  - ./config-pvc.yaml
  - ./helm-release.yaml
  - ./secret.sops.yaml
  #- ./volsync.yaml
configMapGenerator:
  - name: pmm-config-tpl
    files:
      - ./configs/config.yml
  - name: pmm-prerolls
    files:
      - ./configs/Pre-rolls.yml
  - name: pmm-scripts
    files:
      - ./scripts/run.sh
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: plex-meta-manager
      app.kubernetes.io/instance: plex-meta-manager
