---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-server
  namespace: media
spec:
  values:
    initContainers:
      immich-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.8@sha256:dfddde81c0d49da09da1e893c95c32934333baba60edde707be5010dc3baa4c2
        env:
          - name: INIT_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_HOSTNAME
          - name: INIT_POSTGRES_DBNAME
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_DATABASE_NAME
          - name: INIT_POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: POSTGRES_SUPER_PASS
          - name: INIT_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_USERNAME
          - name: INIT_POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_PASSWORD
