---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-org
resources:
  - ./configmap.yaml
  - ./nfs-pvc.yaml
  - ./secret.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/part-of: immich
