ansible_become_pass: ENC[AES256_GCM,data:vFv9xaDM,iv:HZo4ywU1sqpZD/j5lctMor+3tZ7r+OSn1hSAqkWT6uU=,tag:exw0dOOnpOBGZPawZWdDbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcVMyV0wyQ2RlT29GUy83
            ejRjWk91Sms5cDQ3K2hmQzJabG9lemNlQkJJCmJRbm1PamlmVmduOVJnS0U4N3NZ
            Z3FMTjAyTTNRdGx6NUtBYTRwdVRTWGsKLS0tIHFTZExROWVFUUZobEJNTEk2SThh
            Zlc0N1Rhd0wvME5RNjQ4T2F4S0FsQlUK+axFO7NoC7ePwoHWCMncGrHG8nl4stDg
            0TZGXLFyzrinjs33UET2+j7G+/aGuKNnaudvr3xTJ/q56py0EnlIig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T14:35:39Z"
    mac: ENC[AES256_GCM,data:fTNXdXxqga/PcrTHFlxMLG/GV/8md7xUiT74jLZj4/YQFJcfayle/E0etXPB9q3b1687+EY9MJ5OtF3eXlHzHr5FmtlkwtGOllAPa/BZWEnDWiT8adFAmEH8og0U2+G3bvBMd6K5fIm5w6S+yM1oQf/POatNe8F/km2GoQltM5w=,iv:XjAMptyWIh2El99gmEhqpvPblFZ0NG3CEvqDBlAT8Sk=,tag:caRZ3BNSlDONmWxLvBGOcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
