ansible_become_pass: ENC[AES256_GCM,data:w7kr5fUN,iv:e0QtS9k26qMh7x6E+uw16b/lP8zGoAtkK3QwZZIQwkk=,tag:zwOlNwJ4Si8W2K2RKC1pCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMFdkaTE1MVJrNUdTaWtK
            b0dsSU1GcHhhRDJlcVFtQUFaeDZ6NmJFZUNVCmo0YnY5WTVwcGo2M0RIRmg5SHUv
            eWxjdmJhUHcrSEpxUHNraktVVzFPbFkKLS0tIElVY1NmYndGN1ArZVJCcklScC9q
            OHpjNU9xQUsvWjBhS3duSWxqSlIyWWsK1zqgIh+2857UfHiw188Y9YZ9jNDvFmzb
            htgB7EObeN/QeL+DrV/3hQHrTU6CzJAm3qi/6miVisBHwUbzrEjr1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T14:35:37Z"
    mac: ENC[AES256_GCM,data:gAW6mNdlBcuXUBVtskwqFwoIwSLDO/ZHWu601EnstrWPGROcDwNzm1C2tV8fcpfMsTpcgMEm5O/gbRz+xnGMaa/kNX8yGhVo4AFA+mGqw2aUGAKgi/ETOWe1bk4/xSthKYAsKw6JoL6MC2cDqMn8ln3hErPbIKhEd4e4mK4vAUk=,iv:Kk82td9i+hImAdRJEOayxXjx59MYaq1b9lLib84M8uc=,tag:OGGDjF0pKAVQDYvUx1gNSg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
