apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:33qq6x+z1xDZQrxp5sFRnec2hP922Iyn,iv:ojdVW+9fxcESmJpwAMOEgha2rhU7XZ3bblOXX/D92ms=,tag:YnUvI4GH9+jzGIP01+ff7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOUV5SnZuR0tuQ3FBOHNz
            SDI5RWtuYWVxakM5THJzWHRZZUw2OTViZEVvCnFxcTZFMWo4dVdCUnF4T2NRZmY3
            czlDWTMwM1hsdXc0WEdPcDJrd1VWTFUKLS0tIEFSc1NaeDU0Q2NEYXZ4TzVhM0Qx
            YklYWVJQYWQxZ0xZOVpMdmNTSTdOWHMK8JtpH1YDHShnucqjjDareQesZlbBF/Si
            VhcNLbNmTdoI59Mw+FL5mFwX1sxX7vKsWjrhwBnPAZJxdkbG/Khn6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-08T14:29:28Z"
    mac: ENC[AES256_GCM,data:oHC1ulVP7w8ijbW/a5aPczcn3ufaISB+R7kKhRlLlmX4ZVXxIQ6Jwn1Z7TqxhKn9OULrOwMR1hyJaCCw3jFswmd3oih73s9PdXwfP08sk25YFPBOzR/ck+GmLlnWa8NxTNBwQz9LhOUTOavKPs4o1BcVE+YImUXooJGX5HWPnF8=,iv:H5l+DbQsivcxy0EgY8S/8O1kYnmXFod9r4RNnzxj208=,tag:cLOJyhviMI37yp6dFuh39Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
