apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UyriIkF2fg0Okskn4g03+/bBPTUsvTrv,iv:CN6c6ZN+cXfjG2Rl+dGjwduUO+SejzXbpp9FMGqbqAY=,tag:zVGLBrcfviV5aj66F7Axig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMXk3T2orWXh5VnMyMXdW
            YUltQnBJV00xcVhzM0dRR0JUVmFzd1dESW1NCjBVOG0zM2VNWTI5YXlKaUMraVhP
            aXBXV010a3h5MVF6OW5TWUgvV0ZkVjQKLS0tIGNNNmRNZzl6QUNQdmtnQ2F0Y0JO
            MW1nRDE2bTFXTU1sTi9jN1ZMKzRwZ1UKwGSFzG3OZueoAi2xG0VGgDJTb0+wKn5I
            iOLl+JgJdp5Oklpuxt4gvEZTgUd1gILGFlQwX5yOOJZ1b0oiFoBRTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T11:27:42Z"
    mac: ENC[AES256_GCM,data:6qbAwS2KDQ9/Xr014yy1+ejRWDJBtWUWPZUo8+13N2QzovcdhR6s3sRuciPf6NvtSzebmJtsbeg889TNbBzlnQ9hQpC8CqnVePBcxEf5V0lg4nhwgr9czeSPKHSPjSLJczjlnPJBrNbNhEuEjomtag+2UUwmUw8HPtwLlE9HZbU=,iv:DfoVnvHctiufBwXwZ3BZMtAJPCwplrWHbSpV7GA/qWQ=,tag:FyklfhoXHSSigILOHZOenw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
