---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: hashicorp
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: vault
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 5m

  values:
    metrics:
      enabled: true
    service:
      enabled: true
    server:
      enabled: true
      image:
        repository: "hashicorp/vault"
        tag: "1.13.2"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotation:
          ingress.home.arpa/type: "external-auth"
        hosts:
          - host: &host vault.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: local-path

      auditStorage:
        enabled: true
        size: 10Gi
        mountPath: "/vault/audit"
        storageClass: local-path

      extraEnvironmentVars:
        TZ: ${TIMEZONE}
        # VAULT_ADDR: "http://127.0.0.1:8200"

      resources:
        requests:
          memory: 256Mi
          cpu: 250m

      standalone:
        enabled: false

      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true

    ui:
      enabled: true
      annotations:
        ingress.home.arpa/type: "external-auth"
      hosts:
        - host: &host-ui vault-ui.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host-ui
    csi:
      enabled: false
