---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  # - ./backup
  - ./config-pvc.yaml
  - ./helm-release.yaml
# configMapGenerator:
#   - name: wireguard-config
#     files:
#       - ./qbittorrent-CH-DE-1.conf
# generatorOptions:
#   disableNameSuffixHash: true
