apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:lVZmYSI+AaP1rNN0ZouqJDMO04feJz85,iv:I7HF227VYkLTjUPJJR4SOOgbDTgGx+muR/8ggPUuIU8=,tag:jwYVomYj6KQhTMu5V553PA==,type:str]
    admin-user: ENC[AES256_GCM,data:ctfLm3I=,iv:uC86FF//y1PnqBLKwRAkeZcie6Q9lsTFWMqR7/puS24=,tag:BV/fggwoXhWLfQ3nMuhc/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxazBOcVBhejBPMGtVUEFZ
            NnBwa2grQ2dTRStyMTY5QW82cWhTVlBBMDNvCjVyM3lxdVJhTVIzTHQ1QkkvZHN2
            UFFvYmV5emFxZDJhMk1KVUd0UlBpU2cKLS0tIFNLdVZ6ZUZkQTR0VGFiOHFrRWlH
            NGNQTDlLMEZKMUZEL1F1bk9DNHZaS28K/MDiUe0F6x49i1HCjNVuCL/q1BYxghjZ
            iRyQ1BtJFcQOmkWQsZfTrBPFLKKemcKmIVjTolNhWM+ZQVgVgTJo/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-08T14:29:29Z"
    mac: ENC[AES256_GCM,data:ZE6w6o1lJFb8K4T2buSwU9WIhyi6EGnwFCPa/8/KP9VoFPS4L5/cj5BVcW0sjVWFsWWR12AsiUU5t8uwU4/t7lBfFWVgbO7ila3FjiB2CmuT0frDtZe+uYcXXKFLRRDmJUswNboO8Ac8wkXaivqDg5KwUyMSwutAnMGU8ZJ7I0A=,iv:8MVqMzXDxAbr8mTKstEGewf2iMXsQrl+qllixvLT7eA=,tag:Lj6QEjjx5mrH5GUbssEx4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
