---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 1Gi
