---
# https://docs.cilium.io/en/latest/network/l2-announcements
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  # NOTE: This might need to be set if you have more than one active NIC on your nodes
  # interfaces:
  #   - ^eno[0-9]+
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  cidrs:
    - cidr: "10.1.99.0/24"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 10.1.99.1
        peer-asn: 65551
        my-asn: 65552
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 10.1.99.90-10.1.99.120
