---
server:
  host: 0.0.0.0
  port: 7441
  apiToken:
    valueFrom:
        secretKeyRef:
          name: omegabrr-secret
          key: OMEGABRR_APIKEY

schedule: "0 */8 * * *"

clients:
  autobrr:
    host: http://autobrr.media.svc:7474
    apikey:
      valueFrom:
        secretKeyRef:
          name: omegabrr-secret
          key: AUTOBRR_APIKEY

  arr:
    - name: radarr
      type: radarr
      host: http://radarr.media.svc:80
      apikey:
        valueFrom:
        secretKeyRef:
          name: omegabrr-secret
          key: RADARR_APIKEY
      filters:
        - 1 # movies

    - name: sonarr
      type: sonarr
      host: http://sonarr.media.svc:80
      apikey:
        valueFrom:
        secretKeyRef:
          name: omegabrr-secret
          key: SONARR_APIKEY
      filters:
        - 2 # shows
      excludeAlternateTitles: true
