---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-config-pvc
  namespace: selfhosted
  labels:
    snapshot.home.arpa/enabled: "false"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: local-path
