---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-selfhosted-n8n
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/selfhosted/n8n/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
