---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.20@sha256:12054ddfb7ca2f18a91080ade305d510d83ce1c81997dc5259029fd1068da7eb

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    enableServiceLinks: false

    env:
      CACHE_DIR: /cache

    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        annotations:
          ingress.home.arpa/enabled: "external-auth"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/calibreweb/nord.css"></head>';
            sub_filter_once on;
        ingressClassName: nginx
        hosts:
          - host: &host calibre-web.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *host
      kobo:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host_kobo calibre-kobo.${SECRET_DOMAIN}
            paths:
              - path: /kobo/
        tls:
          - hosts:
              - *host_kobo

    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-pvc
      ## TODO
      # media:
      #   enabled: true
      #   mountPath: /data/media
      #   existingClaim: media-nfs-share-pvc
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache

    resources:
      requests:
        cpu: 15m
        memory: 249M
      limits:
        memory: 299M
