---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  # - ./backup
  - ./helm-release.yaml
  - ./config-pvc.yaml
commonLabels:
  app.kubernetes.io/name: calibre-web
  app.kubernetes.io/instance: calibre-web
