---
kubernetes:
  children:
    master:
      hosts:
        kube1001:
          ansible_user: debian
          ansible_host: 10.1.100.11
        kube1002:
          ansible_user: debian
          ansible_host: 10.1.100.12
        kube1003:
          ansible_user: debian
          ansible_host: 10.1.100.13
    worker:
      hosts:
        kube2001:
          ansible_user: debian
          ansible_host: 10.1.100.21
        kube2002:
          ansible_user: debian
          ansible_host: 10.1.100.22
        kube2003:
          ansible_user: debian
          ansible_host: 10.1.100.23
        kube2004:
          ansible_user: debian
          ansible_host: 10.1.100.24
