apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:VTecXf7gSotA0sdWP5ri/ok6oBhTGEzHfghJMKJBPZpm/j58altBAg==,iv:SHzW96phQA3pVcV5YRcDj2+tqUj6JDBezUUv8ljgECA=,tag:18LY1xN4CGV2Hh+AceY7vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWnlmdFloSkVRRWVGVnZH
            dGdYaTMxOFdLR3M4MDBOdHV3R3A4eklzTW40Cm4zN1ZsTzgzZm1YeDV2THRXdi9j
            Vnp3cXZ3L1dFRUZyTkw5WDRKcWlGbTQKLS0tIDFqaUZLeDdvOHNIaEI0V2l1Uks0
            elBSN0dPRi9GTGEzem5MQkRsQWM0dFkKEv+9pbSxbkoU/NZ159LwnmdrlexLX7kl
            WzAbL9KoDRF2XTWu4kJ2ip5HgkUfWYSPZ/OV3kVaS0jUx5EIgFN+wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-08T14:29:29Z"
    mac: ENC[AES256_GCM,data:okDzp3yy+VzvQ/FPJykEwenDskkCYNLFBqPVWU9MLhX/lepXxDnI9tpMu1j+13fxDDCwvkDgbkzCiXTupXDuFqlb7R4iwkMxihFi3KzR4kPfYHxXX7JW/yxwNRVREkuK1ftoJz3oAAoutx9WdwdYdHLD3KWutHCAiwvts4GAtPY=,iv:EkhbERPgri8olInqnxp3T8DvUYl5CHWyuJB98Ffmnok=,tag:lOkLuYz5tVaEYIht2UfmxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
