---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./helm-release.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - files:
      - ./config/configuration.yml
    name: authelia
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: authelia
      app.kubernetes.io/name: authelia
patches:
  - path: ./patches/env.yaml
  - path: ./patches/postgres.yaml
