#yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pod-gateway-secret
    namespace: vpn
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ewTMIDo4OO+z3EMU2NCbtShcJlQydUUZQdlb+Ryw4PIBop1d00QETHK7NEY=,iv:zHlqagSaeJrqMoHEilJfRs82acrA4eLZ035N2IP9s9U=,tag:tEz0SNQLAX0itSNw47vYtA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:PWksHON1ja0pibXmfx2dhCUReW2w8UKR1iHRXlgIi4Ag1MQzETPSRWwPQYI=,iv:fhATw3OquxekWthj6bado15B8BQJQjjePkVMaelk+J4=,tag:aQCgDWNqoKhjapLc4vtjiA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:d/dOikRrBUI5TFI=,iv:Q2X0hqRa6ubLjHMRghDwLe5T8x2F83ABd/VwgKEBZH0=,tag:VU39/rjP/hRzPaL7ZrKyBg==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:I/WUBf0BvY5nRMxK61+6,iv:8IH7+CkcTsetTaMTjUXtCcjaCZpPbo+cyFf7UHaYsis=,tag:3gnNdeYboF1BWWjBQn9rjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cGJNYWx6MnF0N3dVZkxh
            WkNNN0IzVy81OFJ5UDNLbUdYamN6QkkzazJvCm1yZ0pkb0R0MDRSZk84b0JrNFJy
            M3RsdUJVNlJVMm5Sck9KN1FuRFU0bjgKLS0tICt4RVN2akh2UFB3UFFaUnVaOTI4
            S2xpLzhISTV1YlZaN2RlQUFQTERNZWMKXIjtQS7js1wwhHQnEe0BedKTt/UI0JxV
            7F+gm6oFy38JrJJJnCTS6Lo8ruBqO1fA1LprSQJZ9y2p57nUJE6WJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-20T12:13:46Z"
    mac: ENC[AES256_GCM,data:ITiHTE3t8p5NMMlbPrxjAunQFomjET7kXm7oh8qw7T9YyGnU91nCvEUavBtFw4fRaOYTik+WzT06vMo2jOIweQEQUBRZDnaXIc08lbSM1mPRB+JqF/wuXHzAp0KgNnz+DisAFTgpSdCCZ61NvylJ8EP0f+ch3hxxV15RsVAfW0Q=,iv:UYxEkeb0tVi441sqpCYifdTd3DsC/nFVQm0QYDVPpt8=,tag:26I5IVAHcu0x8ZnXpOulXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
