---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-security-authelia-app
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/security/authelia/app
  prune: true
  dependsOn:
    # - name: cluster-0-apps-security-authelia-redis
    - name: cluster-0-apps-cloudnative-pg-cluster
    - name: cluster-0-apps-cloudnative-pg-app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-security-authelia-redis
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/security/authelia/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
