---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-app
  namespace: flux-system
spec:
  path: ./kubernetes/apps/db/cloudnative-pg/app
  prune: true
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-cluster
  namespace: flux-system
spec:
  path: ./kubernetes/apps/db/cloudnative-pg/cluster
  prune: true
  dependsOn:
    - name: cluster-apps-rook-ceph-add-ons-dash
    - name: cluster-apps-rook-ceph-add-ons-direct-mount
    - name: cluster-apps-rook-ceph-app
    - name: cluster-apps-rook-ceph-operator
    - name: cluster-apps-rook-ceph-sc-base
    - name: cluster-apps-rook-ceph-sc-config
    - name: cluster-apps-rook-ceph-sc-crds
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
