apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:iYDZ2q5nBILhEGN/PmIDEa7W+E0onfoQstBP6Q==,iv:a6u2T0Le/OeYR4rRIgdaBB9Yf9+uQ7PABDLM8i4OvIw=,tag:bHsQy2EDM1JcQFr5pKUjXg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:INtTUbbNx4lDs9Fx69fU5u3gGcsFhGMrJWX8uRto4vvuQdb4,iv:/ISoUoM2Q1rXdE8iaozSJ7fPGh6hMRFCsqCqrANtT8I=,tag:ZMwKDRy48O/Ysl1t0X+PLg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:NJkHEJK/UsI72bY=,iv:Za5FptQCckbYhAkuGl+iAgHJLT/Us4VZWPmTBPcD2qQ=,tag:Sl74mIme/JfWIr3iilL+PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UkdoWWN6WEZqakNoZnU4
            aG5WbmtRMGdnc3hVVTBJM1kxaDhSbHBuZURJCm1LdFo3aUdnR3VPQnYyWDZRNkl4
            QXRpSVhLcm1INm9RV085RlVtMUhLYk0KLS0tIFg3eDFoOG5oOXRFWmlHdHduTDVE
            d1VZR2xEWmwzR003a2x6Z1o0VEgzL2sK4o2UbnSYUUgdWXb7IHVzUlHQJgKzb5K3
            M0iNQF8n8sfdcd8Ed/f70yJRI5WCM2RHmOeFF9/lDu6X+RbUrZg4mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T11:27:41Z"
    mac: ENC[AES256_GCM,data:HOYa37qELCM7iPNUuaYTrJraIEmRMB2yXhnA9viOaTiHwz8rkSxWWenQJX1eFadpJEIaurCBTqgxtXKon4t3qcCMFbr/cWJL6o9DJ1AFuk5rpqNCcbE0FC6W3iCgr3EaqVpI5BnDEPS+j1xIb8Z0zCwAttqBiet4alr2JqGmyc0=,iv:oD/+k8gSWb38yy7FjRVMu/jM6ZncDltP/oNc8qfB9lI=,tag:JvJgJjpfXer02ZYldtUzmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
