---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-browser-config-pvc
  namespace: media-org
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
