---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-browser-nfs
spec:
  storageClassName: media-browser-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.perth.labcloud.cc
    path: /mnt/Data
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-browser-nfs
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: media-browser-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
