---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-share-pvc
  namespace: vpn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
  volumeName: media-nfs-share-pv
