---
# yaml-language-server: $schema=https://kubernetes-schemas.ergho.org/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-downloaders-qbittorrent-vpn
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-0-apps-vpn-pod-gateway
    # - name: cluster-apps-rook-ceph-cluster
  path: ./cluster-0/apps/downloaders/qbittorrent-vpn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: qbittorrent-vpn
      namespace: downloaders
  interval: 30m
  retryInterval: 1m
  timeout: 3m
