kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: excalidraw
    namespace: selfhosted
stringData:
    EXCALIDRAW_S3_ENDPOINT: ENC[AES256_GCM,data:Uyoobw==,iv:SL4xnSKxjBS83GebUzq/J2qcR/3P/cv4DH02AgyvdsY=,tag:4GlSy6TKn+7zrBK6DmrrYw==,type:str]
    EXCALIDRAW_S3_BUCKET_NAME: ENC[AES256_GCM,data:nF135A==,iv:bcmZ/QkQyOCetJNYK0vmsSsJpIbLRcXgGhBoZcknzpw=,tag:8XYQl5UWfkXKE32vMe9UGg==,type:str]
    EXCALIDRAW_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:n9AOLQ==,iv:y+MKcn/kPYdsqHBDONhINWXCLztO4NdRnIGinyRKnWI=,tag:1tA49JHw1FIm361vajSWZw==,type:str]
    EXCALIDRAW_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tqX7sw==,iv:DpVLlH1tH4pI2abc8N6KUL9QMSxWOBBzNs6C3/NzIos=,tag:6UslWmOS7YSBAaozvinnzw==,type:str]
    EXCALIDRAW_S3_FORCE_PATH_STYLE: ENC[AES256_GCM,data:cwafM7s=,iv:wrBBoopQ351x0oMRS3yjGoYKSPolVyklt0Hj9t5b4/I=,tag:Tl9LxZDhbaQrCh6ndYMmdQ==,type:str]
    #ENC[AES256_GCM,data:OV67MfQ6tFAXHw==,iv:u5YbRbw2bkrBaa6J6GAfmMMypbPQ2KqP2YHWilYWMa4=,tag:Y2BQX1xiJgDJ+XY0Z/Qjng==,type:comment]
    EXCALIDRAW_ALLOWED_ORIGIN: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGU0s0bC81SUgzOGd1V05F
            Y3pnOGpQS2xXVFVkd243U3YrK1pTWGtRWmtRCk5qc1VFOTlna2YyRXVHUkRqWjdL
            ODQ1bjVNWDFqZE1OTXlLME1Tb3BzWDgKLS0tIEZTT3FlSi9xU2ZUOCs5YXVoTzgw
            QnRHa3hJUFpQMm1MczVyVis4OVhBbXMKdEdDgFLO71WucR7B1Ck9cwA8S1peh3Ek
            pEvmYHBQqdI+jhXMoUFgmSXBKyehLCVJC1v6TvYxr/dp8iRxPX+ulg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-15T05:10:12Z"
    mac: ENC[AES256_GCM,data:nQkO1vlm/Zio2bARHS5W9MvJwUJfU40IopnE8RbO+YPp1L1hX5SF3J6bFoBetHw22s3YX4AGnO39C0EHWMJb3k4TuW6nyJ81/xeLn9HKYVBJKfgtytksHDMqMgN84AnFRpsZHZpKteRllFPWFYprvyDb5Z3aaMyirW9BZ/GFHGg=,iv:MeiLfq0lN++e2P73Zrx3DO0s4jTDPed6XV3CZR+W/X0=,tag:2C97BDstNlBz44XakT76Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
