apiVersion: v1
kind: Secret
metadata:
    name: readarr-ebooks
    namespace: media-org
type: Opaque
stringData:
    READARR__API_KEY: ENC[AES256_GCM,data:9TypY6yGGqt5yaN/v4F26KnzOzXDZPBp2dzWGHEUpUFwP5d4sF4mJ3oRweorFnOejxndG3wU47McRFiHu9x+5CPrstdIq6fLM8fmgu7+eko=,iv:fE5XNCHX1XvvHJO3HZgoxSY+MGp10R8xZGYmc3mLt/I=,tag:pRlMwSB4GH155haJdGhqQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbnlCSHBMQ0RJUGF0ZGlN
            WkRiMUEvb2N2L2pXU29BZDlnS3VQUE15ekNFCmZxMjVqTElpOHJSOHFGOEU1UGtv
            MER5Rk4wb0FEWThxbU11VlBYeEJXYjAKLS0tIHorQnJPTHhsQnArVFFtOU9vUElw
            U2dGNmN5UzhIOUVORjR0dVhlWnU2YVkK05BbSv82HKUpcW7naPqSmBKu6xWZhFDJ
            ntyAHXRbjHVFMuU0vuxPr5tIlQI+XEX/rgPuo5b53o4cYotjq3oDJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T15:23:45Z"
    mac: ENC[AES256_GCM,data:slVgiyn3b7zMwpXCrug/AoKi8mE0QFJGDxUGjYeiUkLQVgR3PtvLL6ZYZlJ+I5iMvbOz0PVxW/FKx9CFAl9+obIYy+Ap15KTC0yCmOXgWYbNVeP7JYnZGjhqoewxUoIOdoAmQjndWuxdJjfD3V2AKNi4Er8MhTL++46AjOYL3S4=,iv:f+ajhnMl2YwxHsOfUGfJMKHLstlYAutTBqhK2wEOQm8=,tag:pLR6QcWD1RS1lnTgYJvvsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
