---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: self-hosted-changedetection
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/self-hosted/changedetection/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: rook-ceph-cluster
    - name: system-volsync
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
