---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./hashicorp.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kubernetes-sigs-descheduler-charts.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  - ./rook-release.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
