---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: db
  annotations:
    coredns.io/hostname: postgres.${SECRET_DOMAIN}
spec:
  type: LoadBalancer
  loadBalancerIP: "10.1.1.105"
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres
    role: primary
