---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-mm-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
