---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./helm-release.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: kyverno-dashboard
    files:
      - kyverno-dashboard.json=https://raw.githubusercontent.com/kyverno/kyverno/main/charts/kyverno/grafana/dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
