---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  DB_PORT: "5432"
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  # REDIS_HOSTNAME: redis-lb.media.svc
  # REDIS_DBINDEX: "10"
  REDIS_HOSTNAME: immich-redis.media.svc
  REDIS_PORT: "6379"
  TYPESENSE_HOST: immich-typesense.media.svc
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config
  IMMICH_WEB_URL: http://immich-web.media.svc:3000
  IMMICH_SERVER_URL: http://immich-server.media.svc:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc:3003
  # Below are deprecated and can only be set in the Immich Admin settings
  # OAUTH_ENABLED: "true"
  # OAUTH_ISSUER_URL: https://auth.devbu.io/.well-known/openid-configuration
  # OAUTH_CLIENT_ID: immich
  # OAUTH_CLIENT_SECRET: "${SECRET_IMMICH_OAUTH_CLIENT_SECRET}"
  # OAUTH_AUTO_REGISTER: "true"
  # OAUTH_BUTTON_TEXT: "Login with Authelia"
