---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-media-immich
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/media/immich
  dependsOn:
    - name: cluster-apps-ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-media-immich-ml
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/media/immich/machine-learning
  dependsOn:
    - name: cluster-apps-ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-media-immich-ms
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/media/immich/microservices
  dependsOn:
    - name: cluster-apps-ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-media-immich-redis
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/media/immich/redis
  dependsOn:
    - name: cluster-apps-ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-media-immich-server
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/media/immich/server
  dependsOn:
    - name: cluster-apps-ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-media-immich-ts
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/media/immich/typesense
  dependsOn:
    - name: cluster-apps-ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0-apps-media-immich-web
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-0/apps/media/immich/web
  dependsOn:
    - name: cluster-apps-ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
