apiVersion: v1
kind: Secret
metadata:
    name: readarr-audio
    namespace: media-org
type: Opaque
stringData:
    READARR__API_KEY: ENC[AES256_GCM,data:JtdfLn4j1lMtRkfOS3bWsajV3jG0hKEY0LFFybYkJg99I7+qCrfx9hO/AUaseWIJUXsxPNh95Ow870LpjuGe8x1Hr2eVzlfH+7uUUljJzO4=,iv:HXMRkYBzEq2Bf7Df+wbEySPk4bN1PZccO/nCrf+3Ef8=,tag:m6GL66o7dBfuhHrCzzLXGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qctq7hfr3jv6vgx73288uukgcc5ug72sv4cuk5zt74kv4hta7qqs7xx0lw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySENGQzB0SDcrajNydXRi
            Sm5OVFo0NXdzZ3lLVXlQR3I2c01VUGVHWG1ZCk5YQ0E3SDk0NFhsbDNqaFZ4Ni9J
            TVVDbGl5STFvb2ZCY2JNTVN2QU1jQ0UKLS0tIEhwMEl6a0JhR2wzTGZScmc1U3hT
            SlRxa016cTVjRXBkYmNiaUZzWmM0Yk0KBc942YRBAG99P5VFWu3PnmPXcWU4EdUr
            SETLFR/5Ljo5HMfLYn55lmDIgEIPNOOCeSrPhZBLSuWlBf1GbNV7TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T15:23:11Z"
    mac: ENC[AES256_GCM,data:WjXloub2GBpAuYj0L7Yc5gWfqt5jsU4lfiejXxh/n7qGfjibpV5Wb2Knb2wQRFLVm/Dol4b8b4XtmzGCed8ATJd/RWKSfGFMOH5zgKkRu9MPo0RbeLkCK/0dtS5vJtCqOxc0Z4oHHFYVwVhmAsERP2LnAdQJnI422at7ND+YAPQ=,iv:g2j6XhY5zUh1a37hVgsKxZq6XuUowrKznrjzU88ia9s=,tag:eOxet59toDMl8/AYn36b5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
