---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.2.4@sha256:fae1b61e2764950e7d6f9c3f74576580d95785292fc6aaa7bcfde8c64e671096
    env:
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          ingress.home.arpa/type: "external-auth"
        hosts:
          - host: &host bazarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-pvc
      media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /data
      # scripts:
      #   enabled: true
      #   type: configMap
      #   name: bazarr-scripts
      #   defaultMode: 0775
      #   readOnly: true
      add-ons:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
    sidecars:
      subcleaner:
        image: registry.k8s.io/git-sync/git-sync:v3.6.8
        imagePullPolicy: IfNotPresent
        args:
          - --repo=https://github.com/KBlixt/subcleaner.git
          - --branch=master
          - --depth=1
          - --wait=21600 # 6 hours
          - --root=/add-ons/subcleaner
        volumeMounts:
          - { name: add-ons, mountPath: /add-ons }
